// Generated by gencpp from file marvin_convnet/DetectObjectsResponse.msg
// DO NOT EDIT!


#ifndef MARVIN_CONVNET_MESSAGE_DETECTOBJECTSRESPONSE_H
#define MARVIN_CONVNET_MESSAGE_DETECTOBJECTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace marvin_convnet
{
template <class ContainerAllocator>
struct DetectObjectsResponse_
{
  typedef DetectObjectsResponse_<ContainerAllocator> Type;

  DetectObjectsResponse_()
    : FrameId(0)  {
    }
  DetectObjectsResponse_(const ContainerAllocator& _alloc)
    : FrameId(0)  {
  (void)_alloc;
    }



   typedef int32_t _FrameId_type;
  _FrameId_type FrameId;




  typedef boost::shared_ptr< ::marvin_convnet::DetectObjectsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marvin_convnet::DetectObjectsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DetectObjectsResponse_

typedef ::marvin_convnet::DetectObjectsResponse_<std::allocator<void> > DetectObjectsResponse;

typedef boost::shared_ptr< ::marvin_convnet::DetectObjectsResponse > DetectObjectsResponsePtr;
typedef boost::shared_ptr< ::marvin_convnet::DetectObjectsResponse const> DetectObjectsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marvin_convnet::DetectObjectsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marvin_convnet::DetectObjectsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace marvin_convnet

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'marvin_convnet': ['/home/pracsys/github/PHYSIM_6DPose/ros-packages/src/marvin_convnet/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::marvin_convnet::DetectObjectsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marvin_convnet::DetectObjectsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marvin_convnet::DetectObjectsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marvin_convnet::DetectObjectsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marvin_convnet::DetectObjectsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marvin_convnet::DetectObjectsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marvin_convnet::DetectObjectsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deed648f5c21fc1f7963eba6909aafea";
  }

  static const char* value(const ::marvin_convnet::DetectObjectsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdeed648f5c21fc1fULL;
  static const uint64_t static_value2 = 0x7963eba6909aafeaULL;
};

template<class ContainerAllocator>
struct DataType< ::marvin_convnet::DetectObjectsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marvin_convnet/DetectObjectsResponse";
  }

  static const char* value(const ::marvin_convnet::DetectObjectsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marvin_convnet::DetectObjectsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int32 FrameId\n\
\n\
\n\
";
  }

  static const char* value(const ::marvin_convnet::DetectObjectsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marvin_convnet::DetectObjectsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.FrameId);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectObjectsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marvin_convnet::DetectObjectsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marvin_convnet::DetectObjectsResponse_<ContainerAllocator>& v)
  {
    s << indent << "FrameId: ";
    Printer<int32_t>::stream(s, indent + "  ", v.FrameId);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARVIN_CONVNET_MESSAGE_DETECTOBJECTSRESPONSE_H
