; Auto-generated. Do not edit!


(cl:in-package realsense_camera-srv)


;//! \htmlinclude StreamSensor-request.msg.html

(cl:defclass <StreamSensor-request> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass StreamSensor-request (<StreamSensor-request>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StreamSensor-request>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StreamSensor-request)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name realsense_camera-srv:<StreamSensor-request> is deprecated: use realsense_camera-srv:StreamSensor-request instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StreamSensor-request>) ostream)
  "Serializes a message object of type '<StreamSensor-request>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StreamSensor-request>) istream)
  "Deserializes a message object of type '<StreamSensor-request>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StreamSensor-request>)))
  "Returns string type for a service object of type '<StreamSensor-request>"
  "realsense_camera/StreamSensorRequest")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StreamSensor-request)))
  "Returns string type for a service object of type 'StreamSensor-request"
  "realsense_camera/StreamSensorRequest")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StreamSensor-request>)))
  "Returns md5sum for a message object of type '<StreamSensor-request>"
  "27bb6b26709cd7555e9a09362b7c10b3")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StreamSensor-request)))
  "Returns md5sum for a message object of type 'StreamSensor-request"
  "27bb6b26709cd7555e9a09362b7c10b3")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StreamSensor-request>)))
  "Returns full string definition for message of type '<StreamSensor-request>"
  (cl:format cl:nil "~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StreamSensor-request)))
  "Returns full string definition for message of type 'StreamSensor-request"
  (cl:format cl:nil "~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StreamSensor-request>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StreamSensor-request>))
  "Converts a ROS message object to a list"
  (cl:list 'StreamSensor-request
))
;//! \htmlinclude StreamSensor-response.msg.html

(cl:defclass <StreamSensor-response> (roslisp-msg-protocol:ros-message)
  ((cloudXYZ
    :reader cloudXYZ
    :initarg :cloudXYZ
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (cloudRGB
    :reader cloudRGB
    :initarg :cloudRGB
    :type (cl:vector cl:fixnum)
   :initform (cl:make-array 0 :element-type 'cl:fixnum :initial-element 0))
   (rawDepth
    :reader rawDepth
    :initarg :rawDepth
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (colorCamIntrinsics
    :reader colorCamIntrinsics
    :initarg :colorCamIntrinsics
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (depthCamIntrinsics
    :reader depthCamIntrinsics
    :initarg :depthCamIntrinsics
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (depth2colorExtrinsics
    :reader depth2colorExtrinsics
    :initarg :depth2colorExtrinsics
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass StreamSensor-response (<StreamSensor-response>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StreamSensor-response>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StreamSensor-response)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name realsense_camera-srv:<StreamSensor-response> is deprecated: use realsense_camera-srv:StreamSensor-response instead.")))

(cl:ensure-generic-function 'cloudXYZ-val :lambda-list '(m))
(cl:defmethod cloudXYZ-val ((m <StreamSensor-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader realsense_camera-srv:cloudXYZ-val is deprecated.  Use realsense_camera-srv:cloudXYZ instead.")
  (cloudXYZ m))

(cl:ensure-generic-function 'cloudRGB-val :lambda-list '(m))
(cl:defmethod cloudRGB-val ((m <StreamSensor-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader realsense_camera-srv:cloudRGB-val is deprecated.  Use realsense_camera-srv:cloudRGB instead.")
  (cloudRGB m))

(cl:ensure-generic-function 'rawDepth-val :lambda-list '(m))
(cl:defmethod rawDepth-val ((m <StreamSensor-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader realsense_camera-srv:rawDepth-val is deprecated.  Use realsense_camera-srv:rawDepth instead.")
  (rawDepth m))

(cl:ensure-generic-function 'colorCamIntrinsics-val :lambda-list '(m))
(cl:defmethod colorCamIntrinsics-val ((m <StreamSensor-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader realsense_camera-srv:colorCamIntrinsics-val is deprecated.  Use realsense_camera-srv:colorCamIntrinsics instead.")
  (colorCamIntrinsics m))

(cl:ensure-generic-function 'depthCamIntrinsics-val :lambda-list '(m))
(cl:defmethod depthCamIntrinsics-val ((m <StreamSensor-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader realsense_camera-srv:depthCamIntrinsics-val is deprecated.  Use realsense_camera-srv:depthCamIntrinsics instead.")
  (depthCamIntrinsics m))

(cl:ensure-generic-function 'depth2colorExtrinsics-val :lambda-list '(m))
(cl:defmethod depth2colorExtrinsics-val ((m <StreamSensor-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader realsense_camera-srv:depth2colorExtrinsics-val is deprecated.  Use realsense_camera-srv:depth2colorExtrinsics instead.")
  (depth2colorExtrinsics m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StreamSensor-response>) ostream)
  "Serializes a message object of type '<StreamSensor-response>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'cloudXYZ))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'cloudXYZ))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'cloudRGB))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:write-byte (cl:ldb (cl:byte 8 0) ele) ostream))
   (cl:slot-value msg 'cloudRGB))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'rawDepth))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'rawDepth))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'colorCamIntrinsics))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'colorCamIntrinsics))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'depthCamIntrinsics))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'depthCamIntrinsics))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'depth2colorExtrinsics))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'depth2colorExtrinsics))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StreamSensor-response>) istream)
  "Deserializes a message object of type '<StreamSensor-response>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'cloudXYZ) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'cloudXYZ)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'cloudRGB) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'cloudRGB)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:aref vals i)) (cl:read-byte istream)))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'rawDepth) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'rawDepth)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'colorCamIntrinsics) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'colorCamIntrinsics)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'depthCamIntrinsics) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'depthCamIntrinsics)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'depth2colorExtrinsics) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'depth2colorExtrinsics)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StreamSensor-response>)))
  "Returns string type for a service object of type '<StreamSensor-response>"
  "realsense_camera/StreamSensorResponse")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StreamSensor-response)))
  "Returns string type for a service object of type 'StreamSensor-response"
  "realsense_camera/StreamSensorResponse")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StreamSensor-response>)))
  "Returns md5sum for a message object of type '<StreamSensor-response>"
  "27bb6b26709cd7555e9a09362b7c10b3")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StreamSensor-response)))
  "Returns md5sum for a message object of type 'StreamSensor-response"
  "27bb6b26709cd7555e9a09362b7c10b3")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StreamSensor-response>)))
  "Returns full string definition for message of type '<StreamSensor-response>"
  (cl:format cl:nil "~%~%float32[] cloudXYZ~%uint8[] cloudRGB~%float32[] rawDepth~%~%~%float32[] colorCamIntrinsics~%float32[] depthCamIntrinsics~%float32[] depth2colorExtrinsics~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StreamSensor-response)))
  "Returns full string definition for message of type 'StreamSensor-response"
  (cl:format cl:nil "~%~%float32[] cloudXYZ~%uint8[] cloudRGB~%float32[] rawDepth~%~%~%float32[] colorCamIntrinsics~%float32[] depthCamIntrinsics~%float32[] depth2colorExtrinsics~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StreamSensor-response>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'cloudXYZ) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'cloudRGB) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 1)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'rawDepth) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'colorCamIntrinsics) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'depthCamIntrinsics) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'depth2colorExtrinsics) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StreamSensor-response>))
  "Converts a ROS message object to a list"
  (cl:list 'StreamSensor-response
    (cl:cons ':cloudXYZ (cloudXYZ msg))
    (cl:cons ':cloudRGB (cloudRGB msg))
    (cl:cons ':rawDepth (rawDepth msg))
    (cl:cons ':colorCamIntrinsics (colorCamIntrinsics msg))
    (cl:cons ':depthCamIntrinsics (depthCamIntrinsics msg))
    (cl:cons ':depth2colorExtrinsics (depth2colorExtrinsics msg))
))
(cl:defmethod roslisp-msg-protocol:service-request-type ((msg (cl:eql 'StreamSensor)))
  'StreamSensor-request)
(cl:defmethod roslisp-msg-protocol:service-response-type ((msg (cl:eql 'StreamSensor)))
  'StreamSensor-response)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StreamSensor)))
  "Returns string type for a service object of type '<StreamSensor>"
  "realsense_camera/StreamSensor")