// Generated by gencpp from file realsense_camera/StreamSensor.msg
// DO NOT EDIT!


#ifndef REALSENSE_CAMERA_MESSAGE_STREAMSENSOR_H
#define REALSENSE_CAMERA_MESSAGE_STREAMSENSOR_H

#include <ros/service_traits.h>


#include <realsense_camera/StreamSensorRequest.h>
#include <realsense_camera/StreamSensorResponse.h>


namespace realsense_camera
{

struct StreamSensor
{

typedef StreamSensorRequest Request;
typedef StreamSensorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StreamSensor
} // namespace realsense_camera


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::realsense_camera::StreamSensor > {
  static const char* value()
  {
    return "27bb6b26709cd7555e9a09362b7c10b3";
  }

  static const char* value(const ::realsense_camera::StreamSensor&) { return value(); }
};

template<>
struct DataType< ::realsense_camera::StreamSensor > {
  static const char* value()
  {
    return "realsense_camera/StreamSensor";
  }

  static const char* value(const ::realsense_camera::StreamSensor&) { return value(); }
};


// service_traits::MD5Sum< ::realsense_camera::StreamSensorRequest> should match 
// service_traits::MD5Sum< ::realsense_camera::StreamSensor > 
template<>
struct MD5Sum< ::realsense_camera::StreamSensorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_camera::StreamSensor >::value();
  }
  static const char* value(const ::realsense_camera::StreamSensorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_camera::StreamSensorRequest> should match 
// service_traits::DataType< ::realsense_camera::StreamSensor > 
template<>
struct DataType< ::realsense_camera::StreamSensorRequest>
{
  static const char* value()
  {
    return DataType< ::realsense_camera::StreamSensor >::value();
  }
  static const char* value(const ::realsense_camera::StreamSensorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::realsense_camera::StreamSensorResponse> should match 
// service_traits::MD5Sum< ::realsense_camera::StreamSensor > 
template<>
struct MD5Sum< ::realsense_camera::StreamSensorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::realsense_camera::StreamSensor >::value();
  }
  static const char* value(const ::realsense_camera::StreamSensorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::realsense_camera::StreamSensorResponse> should match 
// service_traits::DataType< ::realsense_camera::StreamSensor > 
template<>
struct DataType< ::realsense_camera::StreamSensorResponse>
{
  static const char* value()
  {
    return DataType< ::realsense_camera::StreamSensor >::value();
  }
  static const char* value(const ::realsense_camera::StreamSensorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REALSENSE_CAMERA_MESSAGE_STREAMSENSOR_H
