(cl:defpackage detection_package-srv
  (:use )
  (:export
   "UPDATEBBOX"
   "<UPDATEBBOX-REQUEST>"
   "UPDATEBBOX-REQUEST"
   "<UPDATEBBOX-RESPONSE>"
   "UPDATEBBOX-RESPONSE"
   "UPDATEACTIVELISTFRAME"
   "<UPDATEACTIVELISTFRAME-REQUEST>"
   "UPDATEACTIVELISTFRAME-REQUEST"
   "<UPDATEACTIVELISTFRAME-RESPONSE>"
   "UPDATEACTIVELISTFRAME-RESPONSE"
  ))

