(cl:defpackage pose_estimation-srv
  (:use )
  (:export
   "ESTIMATEOBJECTPOSE"
   "<ESTIMATEOBJECTPOSE-REQUEST>"
   "ESTIMATEOBJECTPOSE-REQUEST"
   "<ESTIMATEOBJECTPOSE-RESPONSE>"
   "ESTIMATEOBJECTPOSE-RESPONSE"
  ))

