// Generated by gencpp from file detection_package/UpdateBbox.msg
// DO NOT EDIT!


#ifndef DETECTION_PACKAGE_MESSAGE_UPDATEBBOX_H
#define DETECTION_PACKAGE_MESSAGE_UPDATEBBOX_H

#include <ros/service_traits.h>


#include <detection_package/UpdateBboxRequest.h>
#include <detection_package/UpdateBboxResponse.h>


namespace detection_package
{

struct UpdateBbox
{

typedef UpdateBboxRequest Request;
typedef UpdateBboxResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateBbox
} // namespace detection_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::detection_package::UpdateBbox > {
  static const char* value()
  {
    return "6c74c02d610a74eb8445a13e3f2a9a1e";
  }

  static const char* value(const ::detection_package::UpdateBbox&) { return value(); }
};

template<>
struct DataType< ::detection_package::UpdateBbox > {
  static const char* value()
  {
    return "detection_package/UpdateBbox";
  }

  static const char* value(const ::detection_package::UpdateBbox&) { return value(); }
};


// service_traits::MD5Sum< ::detection_package::UpdateBboxRequest> should match 
// service_traits::MD5Sum< ::detection_package::UpdateBbox > 
template<>
struct MD5Sum< ::detection_package::UpdateBboxRequest>
{
  static const char* value()
  {
    return MD5Sum< ::detection_package::UpdateBbox >::value();
  }
  static const char* value(const ::detection_package::UpdateBboxRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::detection_package::UpdateBboxRequest> should match 
// service_traits::DataType< ::detection_package::UpdateBbox > 
template<>
struct DataType< ::detection_package::UpdateBboxRequest>
{
  static const char* value()
  {
    return DataType< ::detection_package::UpdateBbox >::value();
  }
  static const char* value(const ::detection_package::UpdateBboxRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::detection_package::UpdateBboxResponse> should match 
// service_traits::MD5Sum< ::detection_package::UpdateBbox > 
template<>
struct MD5Sum< ::detection_package::UpdateBboxResponse>
{
  static const char* value()
  {
    return MD5Sum< ::detection_package::UpdateBbox >::value();
  }
  static const char* value(const ::detection_package::UpdateBboxResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::detection_package::UpdateBboxResponse> should match 
// service_traits::DataType< ::detection_package::UpdateBbox > 
template<>
struct DataType< ::detection_package::UpdateBboxResponse>
{
  static const char* value()
  {
    return DataType< ::detection_package::UpdateBbox >::value();
  }
  static const char* value(const ::detection_package::UpdateBboxResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DETECTION_PACKAGE_MESSAGE_UPDATEBBOX_H
