// Generated by gencpp from file detection_package/UpdateActiveListFrameResponse.msg
// DO NOT EDIT!


#ifndef DETECTION_PACKAGE_MESSAGE_UPDATEACTIVELISTFRAMERESPONSE_H
#define DETECTION_PACKAGE_MESSAGE_UPDATEACTIVELISTFRAMERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace detection_package
{
template <class ContainerAllocator>
struct UpdateActiveListFrameResponse_
{
  typedef UpdateActiveListFrameResponse_<ContainerAllocator> Type;

  UpdateActiveListFrameResponse_()
    : result(false)  {
    }
  UpdateActiveListFrameResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;




  typedef boost::shared_ptr< ::detection_package::UpdateActiveListFrameResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detection_package::UpdateActiveListFrameResponse_<ContainerAllocator> const> ConstPtr;

}; // struct UpdateActiveListFrameResponse_

typedef ::detection_package::UpdateActiveListFrameResponse_<std::allocator<void> > UpdateActiveListFrameResponse;

typedef boost::shared_ptr< ::detection_package::UpdateActiveListFrameResponse > UpdateActiveListFrameResponsePtr;
typedef boost::shared_ptr< ::detection_package::UpdateActiveListFrameResponse const> UpdateActiveListFrameResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detection_package::UpdateActiveListFrameResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detection_package::UpdateActiveListFrameResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace detection_package

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::detection_package::UpdateActiveListFrameResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detection_package::UpdateActiveListFrameResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detection_package::UpdateActiveListFrameResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detection_package::UpdateActiveListFrameResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detection_package::UpdateActiveListFrameResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detection_package::UpdateActiveListFrameResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detection_package::UpdateActiveListFrameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::detection_package::UpdateActiveListFrameResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::detection_package::UpdateActiveListFrameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detection_package/UpdateActiveListFrameResponse";
  }

  static const char* value(const ::detection_package::UpdateActiveListFrameResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detection_package::UpdateActiveListFrameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n\
\n\
";
  }

  static const char* value(const ::detection_package::UpdateActiveListFrameResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detection_package::UpdateActiveListFrameResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UpdateActiveListFrameResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detection_package::UpdateActiveListFrameResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detection_package::UpdateActiveListFrameResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECTION_PACKAGE_MESSAGE_UPDATEACTIVELISTFRAMERESPONSE_H
