// Generated by gencpp from file detection_package/UpdateActiveListFrame.msg
// DO NOT EDIT!


#ifndef DETECTION_PACKAGE_MESSAGE_UPDATEACTIVELISTFRAME_H
#define DETECTION_PACKAGE_MESSAGE_UPDATEACTIVELISTFRAME_H

#include <ros/service_traits.h>


#include <detection_package/UpdateActiveListFrameRequest.h>
#include <detection_package/UpdateActiveListFrameResponse.h>


namespace detection_package
{

struct UpdateActiveListFrame
{

typedef UpdateActiveListFrameRequest Request;
typedef UpdateActiveListFrameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateActiveListFrame
} // namespace detection_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::detection_package::UpdateActiveListFrame > {
  static const char* value()
  {
    return "5a8fae94bc9f5cfafa76e73536e515b5";
  }

  static const char* value(const ::detection_package::UpdateActiveListFrame&) { return value(); }
};

template<>
struct DataType< ::detection_package::UpdateActiveListFrame > {
  static const char* value()
  {
    return "detection_package/UpdateActiveListFrame";
  }

  static const char* value(const ::detection_package::UpdateActiveListFrame&) { return value(); }
};


// service_traits::MD5Sum< ::detection_package::UpdateActiveListFrameRequest> should match 
// service_traits::MD5Sum< ::detection_package::UpdateActiveListFrame > 
template<>
struct MD5Sum< ::detection_package::UpdateActiveListFrameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::detection_package::UpdateActiveListFrame >::value();
  }
  static const char* value(const ::detection_package::UpdateActiveListFrameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::detection_package::UpdateActiveListFrameRequest> should match 
// service_traits::DataType< ::detection_package::UpdateActiveListFrame > 
template<>
struct DataType< ::detection_package::UpdateActiveListFrameRequest>
{
  static const char* value()
  {
    return DataType< ::detection_package::UpdateActiveListFrame >::value();
  }
  static const char* value(const ::detection_package::UpdateActiveListFrameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::detection_package::UpdateActiveListFrameResponse> should match 
// service_traits::MD5Sum< ::detection_package::UpdateActiveListFrame > 
template<>
struct MD5Sum< ::detection_package::UpdateActiveListFrameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::detection_package::UpdateActiveListFrame >::value();
  }
  static const char* value(const ::detection_package::UpdateActiveListFrameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::detection_package::UpdateActiveListFrameResponse> should match 
// service_traits::DataType< ::detection_package::UpdateActiveListFrame > 
template<>
struct DataType< ::detection_package::UpdateActiveListFrameResponse>
{
  static const char* value()
  {
    return DataType< ::detection_package::UpdateActiveListFrame >::value();
  }
  static const char* value(const ::detection_package::UpdateActiveListFrameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DETECTION_PACKAGE_MESSAGE_UPDATEACTIVELISTFRAME_H
