// Generated by gencpp from file detection_package/UpdateBboxRequest.msg
// DO NOT EDIT!


#ifndef DETECTION_PACKAGE_MESSAGE_UPDATEBBOXREQUEST_H
#define DETECTION_PACKAGE_MESSAGE_UPDATEBBOXREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace detection_package
{
template <class ContainerAllocator>
struct UpdateBboxRequest_
{
  typedef UpdateBboxRequest_<ContainerAllocator> Type;

  UpdateBboxRequest_()
    : request(false)  {
    }
  UpdateBboxRequest_(const ContainerAllocator& _alloc)
    : request(false)  {
  (void)_alloc;
    }



   typedef uint8_t _request_type;
  _request_type request;




  typedef boost::shared_ptr< ::detection_package::UpdateBboxRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detection_package::UpdateBboxRequest_<ContainerAllocator> const> ConstPtr;

}; // struct UpdateBboxRequest_

typedef ::detection_package::UpdateBboxRequest_<std::allocator<void> > UpdateBboxRequest;

typedef boost::shared_ptr< ::detection_package::UpdateBboxRequest > UpdateBboxRequestPtr;
typedef boost::shared_ptr< ::detection_package::UpdateBboxRequest const> UpdateBboxRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detection_package::UpdateBboxRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detection_package::UpdateBboxRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace detection_package

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::detection_package::UpdateBboxRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detection_package::UpdateBboxRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detection_package::UpdateBboxRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detection_package::UpdateBboxRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detection_package::UpdateBboxRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detection_package::UpdateBboxRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detection_package::UpdateBboxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f7e5ad6ab0ddf42c5727a195315a470";
  }

  static const char* value(const ::detection_package::UpdateBboxRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f7e5ad6ab0ddf42ULL;
  static const uint64_t static_value2 = 0xc5727a195315a470ULL;
};

template<class ContainerAllocator>
struct DataType< ::detection_package::UpdateBboxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detection_package/UpdateBboxRequest";
  }

  static const char* value(const ::detection_package::UpdateBboxRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detection_package::UpdateBboxRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool request\n\
";
  }

  static const char* value(const ::detection_package::UpdateBboxRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detection_package::UpdateBboxRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UpdateBboxRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detection_package::UpdateBboxRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detection_package::UpdateBboxRequest_<ContainerAllocator>& v)
  {
    s << indent << "request: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECTION_PACKAGE_MESSAGE_UPDATEBBOXREQUEST_H
